# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - script: |
      npm run build
    displayName: "npm build"

  - task: Docker@2
    inputs:
      containerRegistry: "MIA_CONSOLE_ACR_SC"
      repository: "callabe-lab/mws-messages"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: "$(Build.SourceBranchName)"
